// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-MXNfMU-m7xksT_93A26CG0iXtN3ftEw',
    appId: '1:389231849741:web:0da857d756a5a7a5838044',
    messagingSenderId: '389231849741',
    projectId: 'myapp-7f393',
    authDomain: 'myapp-7f393.firebaseapp.com',
    storageBucket: 'myapp-7f393.firebasestorage.app',
    measurementId: 'G-CQCK54BFVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTo75HQ6kQuqlcJRGZa_3OZFCi20QA8jM',
    appId: '1:389231849741:android:9edc5dd586191990838044',
    messagingSenderId: '389231849741',
    projectId: 'myapp-7f393',
    storageBucket: 'myapp-7f393.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdx5q0P9nx144UjnirwDOw4lYv6ZwwsxU',
    appId: '1:389231849741:ios:c9d43ec34fb9e72c838044',
    messagingSenderId: '389231849741',
    projectId: 'myapp-7f393',
    storageBucket: 'myapp-7f393.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-MXNfMU-m7xksT_93A26CG0iXtN3ftEw',
    appId: '1:389231849741:web:737a49b188b9d4f9838044',
    messagingSenderId: '389231849741',
    projectId: 'myapp-7f393',
    authDomain: 'myapp-7f393.firebaseapp.com',
    storageBucket: 'myapp-7f393.firebasestorage.app',
    measurementId: 'G-C7Q639W6LB',
  );
}
